use crate::cli::Cli;

/// Generates a usage spec for the CLI
///
/// https://usage.jdx.dev
#[derive(Debug, usage_derive::Args)]
#[usage(effect = "read")]
pub struct Usage {}

/// The spec written to communique.usage.kdl, shared by `communique usage` and
/// the test that keeps the checked-in copy in sync.
fn generate_to_string() -> String {
    format!(
        "// @generated by `communique usage`\n{}",
        Cli::to_kdl().trim_end()
    )
}

impl Usage {
    pub fn run(&self) -> miette::Result<()> {
        println!("{}", generate_to_string());
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `run` is thin, but it is the only path that actually emits the spec —
    /// leaving it untested meant nothing checked that `communique usage`
    /// succeeds at all.
    #[test]
    fn run_succeeds() {
        assert!(Usage {}.run().is_ok());
    }

    #[test]
    fn test_usage_kdl_in_sync() {
        let generated = generate_to_string();
        let on_disk = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("communique.usage.kdl"),
        )
        .expect("communique.usage.kdl should exist");
        assert_eq!(
            generated.trim(),
            on_disk.trim(),
            "communique.usage.kdl is out of sync — run `cargo run -- usage > communique.usage.kdl` to update"
        );
    }

    /// The spec still parses as a spec, which is the whole reason it is emitted.
    ///
    /// `usage` reads it to generate completions, docs and a manpage, so a spec that
    /// only *looks* right is a CLI whose tooling silently stops working.
    #[test]
    fn the_spec_is_a_spec() {
        let spec: usage::Spec = generate_to_string().parse().expect("a valid spec");
        assert_eq!(spec.bin, "communique");

        // The effects survive the trip, which is what `command_effects.rs` used to apply by
        // hand and what a consumer reads to decide whether to prompt.
        let effect = |name: &str| spec.cmd.subcommands.get(name).expect(name).effect;
        assert_eq!(effect("init"), Some(usage::SpecCommandEffect::Write));
        assert_eq!(effect("generate"), Some(usage::SpecCommandEffect::Read));

        let generate = spec.cmd.subcommands.get("generate").expect("generate");
        let force = spec.cmd.subcommands.get("init").expect("init");
        assert_eq!(
            generate
                .flags
                .iter()
                .find(|f| f.name == "github-release")
                .expect("--github-release")
                .effect,
            Some(usage::SpecCommandEffect::Write),
            "a flag raises what its command does"
        );
        assert_eq!(
            force
                .flags
                .iter()
                .find(|f| f.name == "force")
                .expect("--force")
                .effect,
            Some(usage::SpecCommandEffect::Destructive)
        );
    }
}
