name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
      - run: rustup component add clippy rustfmt
      - uses: taiki-e/install-action@cd1c8251b429e645b6b4fef021814af1150c1f22 # cargo-audit
      - run: mise run lint
      - run: mise x -- cargo test
      - run: cargo audit

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
      - run: rustup component add llvm-tools-preview
      - uses: taiki-e/install-action@d79fce544138636ae8155ecac335f73c98e3b198 # cargo-llvm-cov
      - run: mise x -- cargo llvm-cov --codecov --output-path codecov.json
      - uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6
        with:
          files: codecov.json
